
name: Bot Local (Retailers Difíciles)

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  scrape_local:
    runs-on: self-hosted 

    steps:
      - name: Ejecutar Bot Maestro directamente en la PC
        shell: cmd
        env:
          PYTHONIOENCODING: utf-8
          PYTHONUNBUFFERED: "1"
        run: |
          cd C:\Users\herna\OneDrive\Escritorio\agente_precios
          python bot_maestro.py --retailers "Casa del Audio,Naldo,On City,Castillo,Cetrogar,Coppel,Fravega,Carrefour,Mercado Libre (Tiendas Oficiales)"
